app/views/auth.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from distutils.util import strtobool
from urllib.parse import urlencode, urljoin, urlparse

import requests

from app.models import User, db
from flask import (Blueprint, abort, current_app, redirect, render_template,
                   request, session, url_for)
from flask_login import LoginManager, current_user, login_user, logout_user

login_manager = LoginManager()
login_manager.login_view = 'auth.login'

auth = Blueprint('auth', __name__)

def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and ref_url.netloc == test_url.netloc

@login_manager.user_loader
def load_user(user_id):
    try:
        user_id = int(user_id)
    except ValueError:
        return None

    access_token = session.get('access_token')
    if access_token is None:
        return None

    user = User.query.get(user_id)
    if user is None:
        return None

    domain = current_app.config['DOMAIN']
    verify_credentials_url = f'https://{domain}/api/v1/accounts/verify_credentials'
    headers = {
        'Authorization': f'Bearer {access_token}',
    }
    try:
        response = requests.get(verify_credentials_url, headers=headers)
        response.raise_for_status()
    except requests.exceptions.RequestException:
        return None

    account_json = response.json()
    if account_json is None:
        return None

    try:
        account_id = int(account_json.get('id'))
    except ValueError:
        account_id = None
    user_name = account_json.get('username')
    if user.account_id != account_id or user.name != user_name:
        return None

    has_changed = False

    display_name = account_json.get('display_name')
    if display_name == '':
        display_name = None
    if user.display_name != display_name:
        user.display_name = display_name
        has_changed = True

    if has_changed:
        try:
            db.session.commit()
        except:
            return None

    return user

@auth.route('/login')
def login():
    if current_user.is_authenticated:
        next = session.pop('next', None)
        if not is_safe_url(next):
            return abort(requests.codes['bad_request'])

        return redirect(next or url_for('map.top'))
    elif 'code' in request.args:
        authorization_code = request.args.get('code')
        domain = current_app.config['DOMAIN']
        token_url = f'https://{domain}/oauth/token'
        parameters = {
            'client_id': current_app.config['CLIENT_ID'],
            'client_secret': current_app.config['CLIENT_SECRET'],
            'grant_type': 'authorization_code',
            'code': authorization_code,
            'redirect_uri': url_for('auth.login', _external=True),
        }
        try:
            response = requests.post(token_url, data=parameters)
            response.raise_for_status()
        except requests.exceptions.RequestException:
            return abort(requests.codes['internal_server_error'])

        token_json = response.json()
        if token_json is None:
            return abort(requests.codes['internal_server_error'])

        access_token = token_json.get('access_token')
        if access_token is None:
            return abort(requests.codes['internal_server_error'])

        verify_credentials_url = f'https://{domain}/api/v1/accounts/verify_credentials'
        headers = {
            'Authorization': f'Bearer {access_token}',
        }
        try:
            response = requests.get(verify_credentials_url, headers=headers)
            response.raise_for_status()
        except requests.exceptions.RequestException:
            return abort(requests.codes['internal_server_error'])

        account_json = response.json()
        if account_json is None:
            return abort(requests.codes['internal_server_error'])

        try:
            account_id = int(account_json.get('id'))
        except ValueError:
            account_id = None
        user_name = account_json.get('username')
        if account_id is None or user_name is None:
            return abort(requests.codes['internal_server_error'])

        user = User.query.filter_by(name=user_name).first()
        if user is None:
            user = User()
            db.session.add(user)
            user.account_id = account_id
            user.name = user_name
        elif user.account_id != account_id:
            return abort(requests.codes['internal_server_error'])

        user.display_name = account_json.get('display_name')
        if user.display_name == '':
            user.display_name = None
        try:
            db.session.commit()
        except:
            return abort(requests.codes['internal_server_error'])

        session['access_token'] = access_token
        login_user(user)

        next = session.pop('next', None)
        if not is_safe_url(next):
            return abort(requests.codes['bad_request'])

        return redirect(next or url_for('map.top'))
    elif 'error' in request.args:
        application_title = current_app.config['APPLICATION_TITLE']
        error_message = f"{request.args['error']}: {request.args.get('error_description', '')}"
        return render_template('auth/error.html', application_title=application_title, error_message=error_message)

    try:
        oauth = strtobool(request.args.get('oauth', 'False'))
    except ValueError:
        oauth = False
    if oauth:
        domain = current_app.config['DOMAIN']
        authorize_url = f'https://{domain}/oauth/authorize'
        parameters = {
            'client_id': current_app.config['CLIENT_ID'],
            'response_type': 'code',
            'redirect_uri': url_for('auth.login', _external=True),
            'scope': 'read:accounts',
        }
        return redirect(f'{authorize_url}?{urlencode(parameters)}')
    else:
        application_title = current_app.config['APPLICATION_TITLE']
        instance_name = current_app.config['INSTANCE_NAME']
        domain = current_app.config['DOMAIN']
        instance_url = f'https://{domain}/'
        return render_template('auth/login.html', application_title=application_title, instance_name=instance_name, instance_url=instance_url)

@auth.route('/logout')
def logout():
    if not current_user.is_authenticated:
        return redirect(url_for('map.top'))

    access_token = session.pop('access_token', None)
    if access_token is not None:
        domain = current_app.config['DOMAIN']
        token_url = f'https://{domain}/oauth/revoke'
        headers = {
            'Authorization': f'Bearer {access_token}',
        }
        parameters = {
            'client_id': current_app.config['CLIENT_ID'],
            'client_secret': current_app.config['CLIENT_SECRET'],
            'token': access_token,
        }
        try:
            response = requests.post(token_url, headers=headers, data=parameters)
            response.raise_for_status()
        except requests.exceptions.RequestException:
            return abort(requests.codes['internal_server_error'])

    logout_user()

    return redirect(url_for('map.top'))

app/views/map.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from urllib.parse import urlencode

import requests

from app.models import Area, Spot, User, db
from flask import Blueprint, abort, current_app, render_template, session
from flask_login import current_user

map = Blueprint('map', __name__)

@map.route('/')
def top():
    domain = current_app.config['DOMAIN']

    if current_user.is_authenticated:
        access_token = session.get('access_token')
        if access_token is None:
            return abort(requests.codes['internal_server_error'])

        parameters = {
            'limit': 80,
        }
        followers_url = f'https://{domain}/api/v1/accounts/{current_user.account_id}/followers?{urlencode(parameters)}'
        headers = {
            'Authorization': f'Bearer {access_token}',
        }
        follower_ids = []
        while True:
            try:
                response = requests.get(followers_url, headers=headers)
                response.raise_for_status()
            except requests.exceptions.RequestException:
                return abort(requests.codes['internal_server_error'])

            account_jsons = response.json()
            if not isinstance(account_jsons, list):
                return abort(requests.codes['internal_server_error'])

            for account_json in account_jsons:
                try:
                    account_id = int(account_json.get('id'))
                except ValueError:
                    continue
                account_acct = account_json.get('acct')
                if account_acct is None or '@' in account_acct:
                    continue
                follower_ids.append(account_id)

            next_link = response.links.get('next')
            if next_link is None:
                break
            followers_url = next_link.get('url')
            if followers_url is None:
                break

        user_subquery = User.query\
            .filter(db.or_(User.id == current_user.id, User.account_id.in_(follower_ids)))\
            .filter(User.area_id == Area.id)\
            .exists()
        user_areas = Area.query\
            .filter(user_subquery)\
            .options(db.joinedload(Area.users))\
            .order_by(Area.id)\
            .all()

        areas = Area.query\
            .options(db.noload(Area.users))\
            .options(db.noload(Area.prefecture))\
            .options(db.noload(Area.city))\
            .options(db.noload(Area.cities))\
            .options(db.noload(Area.wards))\
            .order_by(Area.id)\
            .all()
        prefectures = []
        cities = []
        wards = []
        for area in areas:
            if area.prefecture_id is None and area.city_id is None:
                prefectures.append(area)
            elif area.prefecture_id is not None and area.city_id is None:
                cities.append(area)
            elif area.prefecture_id is not None and area.city_id is not None:
                wards.append(area)
        for prefecture in prefectures:
            for city in cities:
                if city.prefecture_id == prefecture.id:
                    city.prefecture = prefecture
                    prefecture.cities.append(city)
            for ward in wards:
                if ward.prefecture_id == prefecture.id:
                    ward.prefecture = prefecture
                    prefecture.wards.append(ward)
        for city in cities:
            for ward in wards:
                if ward.city_id == city.id:
                    ward.city = city
                    city.wards.append(ward)
    else:
        user_areas = []

    spots = Spot.query.all()

    application_title = current_app.config['APPLICATION_TITLE']
    instance_url = f'https://{domain}/'
    mapbox_user_name = current_app.config['MAPBOX_USER_NAME']
    mapbox_style_id = current_app.config['MAPBOX_STYLE_ID']
    mapbox_access_token = current_app.config['MAPBOX_ACCESS_TOKEN']
    return render_template('map/top.html', application_title=application_title, instance_url=instance_url, mapbox_user_name=mapbox_user_name, mapbox_style_id=mapbox_style_id, mapbox_access_token=mapbox_access_token, user_areas=user_areas, spots=spots)

app/views/settings.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import requests

from app.models import Area, db
from flask import (Blueprint, abort, current_app, flash, redirect,
                   render_template, request, url_for)
from flask_login import current_user, login_required

settings = Blueprint('settings', __name__)

@settings.route('/settings/')
@login_required
def top():
    return redirect(url_for('settings.habitat'))

@settings.route('/settings/habitat', methods=['GET', 'POST'])
@login_required
def habitat():
    if request.method == 'POST':
        area_id = request.form['wardid']\
            or request.form['cityid']\
            or request.form['prefectureid']
        if area_id is not None:
            current_user.area_id = area_id
            try:
                db.session.commit()
            except:
                return abort(requests.codes['internal_server_error'])
        flash('設定を保存しました。', 'success')

    application_title = current_app.config['APPLICATION_TITLE']

    prefectures = Area.query\
        .options(db.joinedload(Area.cities).joinedload(Area.wards))\
        .filter(Area.prefecture_id == None, Area.city_id == None)\
        .order_by(Area.id)\
        .all()

    cities = []
    for prefecture in prefectures:
        for city in sorted(prefecture.cities, key=lambda city: city.id):
            cities.append(city)

    wards = []
    for city in cities:
        for ward in sorted(city.wards, key=lambda ward: ward.id):
            wards.append(ward)

    area = current_user.area
    if area is None:
        prefecture_id = None
        city_id = None
        ward_id = None
    elif area.prefecture_id is None:
        prefecture_id = area.id
        city_id = None
        ward_id = None
    elif area.city_id is None:
        prefecture_id = area.prefecture_id
        city_id = area.id
        ward_id = None
    else:
        prefecture_id = area.prefecture_id
        city_id = area.city_id
        ward_id = area.id

    return render_template('settings/habitat.html', application_title=application_title, prefectures=prefectures, cities=cities, wards=wards, prefecture_id=prefecture_id, city_id=city_id, ward_id=ward_id)

app/templates/map/top.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{{ application_title }}</title>
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />

    <script src="https://api.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.css" rel="stylesheet" />

    <style>
      body {
        margin: 0;
        padding: 0;
      }
      #map {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 100%;
      }
      .mapboxgl-ctrl-top-right .mapboxgl-ctrl {
        clear: none;
        float: left;
      }
      .mapboxgl-ctrl-icon.mapboxgl-ctrl-label {
        width: auto;
        height: auto;
        padding: 0.3em 0.5em;
      }
      .spot {
        width: 12px !important;
        height: 12px !important;
        border-radius: 12px;
        border: 2px solid white;
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.8);
        background-color: #2b82cb;
        cursor: pointer;
      }
    </style>
  </head>

  <body>
    <div id="map"></div>

    <script>
      function random(seed, max) {
        let rnd = (seed * 9301 + 49297) % 233280 / 233280;
        return Math.floor(rnd * max);
      }

      function toColor(area_id, is_boundary) {
        let h = (random(area_id, 360)).toString();
        let s = (random(area_id + 1, 31) + 70).toString();
        let l = (is_boundary ? 50 : 80).toString();
        return 'hsla(' + h + ', ' + s + '%, ' + l + '%, 0.7)';
      }

      mapboxgl.accessToken = '{{ mapbox_access_token }}';

      const mt_fuji_latitude = 35.3622222;
      const mt_fuji_longitude = 138.7313889;

      let map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/{{ mapbox_user_name }}/{{ mapbox_style_id }}',
        center: [mt_fuji_longitude, mt_fuji_latitude],
        zoom: 8,
        hash: true,
      });

      map.addControl(new mapboxgl.NavigationControl(), 'top-left');

      map.addControl(new mapboxgl.GeolocateControl({
        positionOptions: {
          enableHighAccuracy: true,
        },
        trackUserLocation: true,
      }), 'top-left');

      class ButtonControl {
        constructor(aria_label, label, href) {
          this._aria_label = aria_label;
          this._label = label;
          this._href = href;
        }

        onAdd(map) {
          this._map = map;
          this._container = document.createElement('div');
          this._container.className = 'mapboxgl-ctrl mapboxgl-ctrl-group';
          this._container.innerHTML = '<button class="mapboxgl-ctrl-icon mapboxgl-ctrl-label" type="button" aria-label="' + this._aria_label + '" onclick="location.href=\'' + this._href + '\'">' + this._label + '</button>';
          return this._container;
        }

        onRemove() {
          this._container.parentNode.removeChild(this._container);
          this._map = undefined;
        }
      }
{%- if current_user.is_authenticated %}

      map.addControl(new ButtonControl('Settings', '設定', "{{ url_for('settings.top') }}"), 'top-right');

      map.addControl(new ButtonControl('Logout', 'ログアウト', "{{ url_for('auth.logout') }}"), 'top-right');
{%- else %}

      map.addControl(new ButtonControl('Login', 'ログイン', "{{ url_for('auth.login') }}"), 'top-right');
{%- endif %}

      map.addControl(new mapboxgl.ScaleControl());

      map.on('load', function () {
{%- if user_areas | length > 0 %}
        let area_filter = [
          "all",
          [
            "match",
            ["get", "id"],
            [
  {%- for user_area in user_areas %}
              {{ user_area.id | safe }},
  {%- endfor %}
            ],
            true,
            false,
          ],
        ];
        map.setFilter('area-polygon', area_filter);
        map.setFilter('area-boundary', area_filter);

        map.setPaintProperty('area-polygon', 'fill-color', [
          "match",
          ["get", "id"],
  {%- for user_area in user_areas %}
          [{{ user_area.id | safe }}],
          toColor({{ user_area.id | safe }}, false),
  {%- endfor %}
          "hsla(0, 100%, 0%, 0)",
        ]);
        map.setPaintProperty('area-boundary', 'line-color', [
          "match",
          ["get", "id"],
  {%- for user_area in user_areas %}
          [{{ user_area.id | safe }}],
          toColor({{ user_area.id | safe }}, true),
  {%- endfor %}
          "hsla(0, 100%, 0%, 0)",
        ]);

        map.on('click', 'area-polygon', function (e) {
          let feature = e.features[0];
          if (!('properties' in feature) || !('id' in feature.properties)) {
            return;
          }

          for (let index = 1; index < e.features.length; index++) {
            const currentFeature = e.features[index];
            if (feature.properties.id < currentFeature.properties.id) {
              feature = currentFeature;
            }
          }

          let area_users_map = {
  {%- for user_area in user_areas %}
            {{ user_area.id | safe }}: {
              name: '
    {%- if user_area.prefecture != None -%}
              {{ user_area.prefecture.name | safe }}
    {%- endif -%}
    {%- if user_area.city != None -%}
              {{ user_area.city.name | safe }}
    {%- endif -%}
              {{ user_area.name | safe }}',
              child_ids: [
    {%- for city in user_area.cities %}
      {%- if city.users | length > 0 %}
                {{ city.id | safe }},
      {%- endif %}
    {%- endfor %}
    {%- for ward in user_area.wards %}
      {%- if ward.users | length > 0 %}
                {{ ward.id | safe }},
      {%- endif %}
    {%- endfor %}
              ],
              users: [
    {%- for user in user_area.users %}
                { name: '
      {%- if user.display_name != None -%}
              {{ user.display_name | safe }}
      {%- else -%}
              {{ user.name | safe }}
      {%- endif -%}
                ', url: '{{ instance_url }}@{{ user.name }}' },
    {%- endfor %}
              ],
            },
  {%- endfor %}
          };

          if (!(feature.properties.id in area_users_map)) {
            return;
          }

          let area_users_pairs = [
            area_users_map[feature.properties.id],
          ];
          for (let child_id of area_users_pairs[0].child_ids) {
            area_users_pairs.push(area_users_map[child_id])
          }

          let area_user_html = '';
          for (let area_users_pair of area_users_pairs) {
            area_user_html += `<h3>${area_users_pair.name}</h3>`;
            for (let user of area_users_pair.users) {
              area_user_html += `<p><a href="${user.url}" target="_blank">${user.name}</a></p>`;
            }
          }

          new mapboxgl.Popup()
            .setLngLat(e.lngLat)
            .setHTML(area_user_html)
            .addTo(map);
        });
 
        map.on('mouseenter', 'area-polygon', function () {
          map.getCanvas().style.cursor = 'pointer';
        });

        map.on('mouseleave', 'area-polygon', function () {
          map.getCanvas().style.cursor = '';
        });

{% endif -%}
        let spot;
        let spot_geojson;
        let spot_html;
{%- for spot in spots %}

        spot = document.createElement('div');
        spot.className = 'spot';
        spot_geojson = {{ spot.geometry | safe }};
        spot_html = '<h3>{{ spot.name | safe }}</h3>{% if spot.description != None %}<p>{{ spot.description | safe }}</p>{% endif %}';
        new mapboxgl.Marker(spot)
          .setLngLat(spot_geojson['coordinates'])
          .setPopup(new mapboxgl.Popup({ offset: 8 })
            .setHTML(spot_html))
          .addTo(map);
{%- endfor %}
      });
    </script>
  </body>
</html>